[package]
name = "MySync"
version = "0.1.0"
authors = ["KTPenrose <kurt@mysync.app>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
